apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
    version: v1
  name: notification-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      version: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-service
        version: v1
    spec:
      containers:
        - image: kubeteam/notification-service:v1
          name: notification-service
          ports:
            - containerPort: 8084
          env:
            - name: HTTP_LISTENING_PORT
              value: "8084"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
    version: v2
  name: notification-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      version: v2
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-service
        version: v2
    spec:
      containers:
        - image: kubeteam/notification-service:v2
          name: notification-service
          ports:
            - containerPort: 8084
          env:
            - name: SERVICE_PORT
              value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8084
  selector:
    app: notification-service